Модуль 4. Спринт 14. Ревью 1.
AAsadova34/java-shareit pull request #2
Opened 2023-01-07 19:38 UTC by AAsadova34

1. Создана БД PostgreSql для хранения данных приложения.
2. Реализована функциональность "Бронирование".
3. Реализована функциональность "Отзывы".
4. Доработана функциональность "Работа с вещами".

2023-01-08 10:13 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> + * TODO Sprint add-bookings.
Этот todo похоже уже не актуален

2023-01-08 19:00 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/booking/dto/BookingInnerDto.java
> +    private LocalDateTime start;
Если есть желание, попробуй использовать @JsonFormat для дат

2023-01-08 19:01 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/booking/dto/BookingInnerDto.java
> + * TODO Sprint add-bookings.
Много где TODO можно удалить, т.к. они уже не релевантны

2023-01-08 19:02 UTC, EvgenyKoptubenko requested changes
Работа сделана отлично. Есть только предложение использовать @JsonFormat

2023-01-09 08:11 UTC, AAsadova34 commented on src/main/java/ru/practicum/shareit/booking/dto/BookingInnerDto.java
> +    private LocalDateTime start;
Спасибо за рекомендацию. Поэкспериментировала с @JsonFormat. Хорошая вещь, но тесты Postman с измененным форматом даты не проходят, поэтому оставила как есть.

2023-01-09 08:33 UTC, EvgenyKoptubenko approved these changes
Работа сделана отлично. Спасибо

2023-01-12 08:48 UTC, merged