Модуль 4. Спринт 16. Ревью 1.
AAsadova34/java-shareit pull request #4
Opened 2023-01-29 17:22 UTC by AAsadova34

2023-01-30 17:59 UTC, EvgenyKoptubenko commented
Замечаний по изменениям в текущем спринте нет, есть замечания по предыдущим спринтам. Если есть желание, поправь, если нет, то присылай - я приму.

2023-01-30 18:00 UTC, EvgenyKoptubenko commented on gateway/src/main/java/ru/practicum/shareit/user/UserController.java
> +    public ResponseEntity<Object> addUser(@Valid @RequestBody UserInnerDto userInnerDto) {
Если добавить пользователя два раза, то приходит 500-я ошибка без объяснения что случилось
{
	"status": 500,
	"decryption": "Internal Server Error",
	"error": "An unexpected error has occurred"
}

2023-01-30 18:03 UTC, EvgenyKoptubenko commented on gateway/src/main/java/ru/practicum/shareit/user/UserController.java
> +    public ResponseEntity<Object> updateUser(@PathVariable long id, @Valid @RequestBody UserInnerDto userInnerDto) {
Если отправить запрос с несуществующим типом, например, PUT, то тоже ошибка 500
{
	"status": 500,
	"decryption": "Internal Server Error",
	"error": "An unexpected error has occurred"
}

Все-таки это неверный запрос со стороны клиента

2023-01-30 18:01:59.351  WARN 1 --- [nio-8080-exec-9] ru.practicum.shareit.log.Logger          : HttpRequestMethodNotSupportedException
2023-01-30T18:01:59.352554036Z 
2023-01-30T18:01:59.352565438Z org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'PUT' not supported

2023-01-30 18:10 UTC, EvgenyKoptubenko commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ResponseEntity<Object> findItemsByNameOrDescription(@RequestHeader(HEADER_CALLER_ID) long userId,
Если передать неверные параметры, то тоже приходит 500-я ошибка 
На самом деле переданы неверные данные
Caused by: java.lang.NumberFormatException: For input string: "фф"

2023-01-30 18:13 UTC, EvgenyKoptubenko requested changes
Замечаний по изменениям в текущем спринте нет, есть замечания по предыдущим спринтам. Если есть желание, поправь, если нет, то присылай - я приму.

2023-01-31 13:27 UTC, AAsadova34 commented on gateway/src/main/java/ru/practicum/shareit/user/UserController.java
> +    public ResponseEntity<Object> addUser(@Valid @RequestBody UserInnerDto userInnerDto) {
Исправила на Conflict. Тесты Postman здесь не примут BadRequest.

2023-01-31 19:30 UTC, EvgenyKoptubenko approved these changes
Работа сделана отлично. Спасибо.

2023-02-01 16:52 UTC, merged